# Album: Bird, Artist: Cherubino, Composer: Travis

dist: xenial
language: python

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

git:
  quiet: true
  submodules: false

python:
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy3.7"

install:
  - pip install -r requirements/install.txt

# - pip install -U .

script:
  - check-manifest -v
  - pytest

notifications:
  email: false