codecov:
  ci:
    - "travis.org"
  require_ci_to_pass: no
  strict_yaml_branch: master
  branch: master

coverage:
  precision: 2
  round: down
  range: "60...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        branches:
          - master
        if_no_uploads: error
        only_pulls: false
        paths:
          - "clu"
          - "clu/"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "docs"
  - "requirements"
  - "scratch"